src/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "splash#splash"

  get "/dashboard", to: "public#index"

  resources :accounts
end

src/app/models/account.rb
class Account < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  has_one_attached :code_image
end

src/app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :accounts, :join_table => :accounts_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

src/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!

  def show
    @account = Account.find(params[:id])
  end
  
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
        # Fields for sign up
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :display_name, :password) }
        # Fields for editing an existing account
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :display_name, :password, :current_password) }
    end

  # Redirects user to their own Posts page after login
  def after_sign_in_path_for(resource)
    posts_path
  end
end

src/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!
  before_action :authorize, only: :edit

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.where(account_id: current_account.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    #Assigns account_id with the id of the current user
    @post.account_id = current_account.id
    @post.code_image.attach(params[:post][:code_image])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.code_image.attach(params[:post][:code_image])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def authorize
      if !current_account.has_role? :admin
        if @post.account.id != current_account.id 
          flash[:alert] = "You are not authorized!"
          redirect_to posts_path
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

src/app/controllers/public_controller.rb
class PublicController < ApplicationController
  before_action :authenticate_account!
  
  def index
    @posts = Post.all
  end
end

src/app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash
  end
end

src/app/helpers/accounts_helper.rb
module AccountsHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/posts_helper.rb
module PostsHelper
end

src/app/helpers/public_helper.rb
module PublicHelper
end

src/app/helpers/splash_helper.rb
module SplashHelper
end

src/app/views/accounts/index.html.erb
<h1>Test</h1>

src/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Display Name:</strong>
  <%= @account.display_name %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', posts_path %>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" <%= link_to "PostCode", dashboard_path %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" <%= link_to "Dashboard", dashboard_path %>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <% if account_signed_in?%>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "My Posts", posts_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Sign Out", destroy_account_session_path, method: "delete" %></a>
          </li>
          <% else%>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Log In", new_account_session_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Sign Up", new_account_registration_path %></a>
          </li>
          <% end %>
          <%# <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li> %>
        </ul>
      </div>
    </div>
  </nav>

  <%# <div class="container"> %>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.slim.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  <%# </div> %>
  </body>
</html>

src/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, :required => true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :code_image %>
    <%= form.file_field :code_image, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

src/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Account</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @post.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.account_id %></td>

        <% if post.code_image.attached? %> 
          <td><%= image_tag post.code_image, width: 600 %></td>
        <% end %>
        <% if current_account.has_role?(:admin) || post.account_id == current_account.id%>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

src/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

src/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Account:</strong>
  <%= @post.account.email %>
</p>

<% if @post.code_image.attached? %>
  <%= image_tag @post.code_image, width: 600 %>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

src/app/views/splash/splash.html.erb
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">PostCode</h1>
        <p class="lead">A social media platform for sharing code snippets. Inspire other developers.</p>
        <p class="lead">Login or register to start your journey.</p>
        <br> <br>
        <%# Sign Up Button. Bootstrap button styling %>
        <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-success btn-lg btn-radius" %>
        <%# Log In Button. Bootstrap button styling %>
        <%= link_to "Log In", new_account_session_path, class: "btn btn-primary btn-lg btn-radius" %>
      </div>
    </div>
  </div>